[Feature][Document] Admin validation WIP
GrottoCenter/Grottocenter3 pull request #355
Opened 2020-10-06 17:22 UTC by maximenathan

Fait:
- Gestion des sous menus 
- Nouveau composant `Table`
- Création de la page `DocumentDetails` _story visible mais pas accècible_
- Création de la page `DocumentValidation` _en lecture_ 
- Accès aux documents depuis le menu admin

En cours:
- Actions `Validation` - `Suppression` d'un document
- Action vue détaillé d'un document
- Pagination non fonctionnel @Clm-Roig  _possible de retourner un objet pagination avec le nombre total d'élément ?)_

2020-10-09 08:06 UTC, Clm-Roig commented on config/locales/en.json
> +  "License": "License",
Pourquoi ce passage de la minuscule en majuscule ?

2020-10-09 08:08 UTC, Clm-Roig commented
Dans la story, le contenu des cases du header du tableau est aligné gauche tandis que le contenu des cellules de données est aligné à droite : je ne trouve pas ça très clair.
![image](https://user-images.githubusercontent.com/20704943/95558997-5fa35f80-0a17-11eb-8e9c-8dba510a5b8b.png)

2020-10-12 17:17 UTC, maximenathan commented on assets/js/react/components/common/Table/TableHead.jsx
> +  return pipe(head, defaultTo({}), keys, map(makeColumn))(rawData);
C'est une question de gout, d'habitude et d'environnement de dev (quand il y a du typage c'est super!)

- Il faut être habitué à la programmation fonctionnel
- Il faut lire la doc au debut (qui est top!) [pipe](https://ramdajs.com/docs/#pipe)

Là le `pipe` c'est comme un compose/sequence.

- [Head](https://ramdajs.com/docs/#head) -> Prend le premier élement du tableau _(de rawData)_ _(=rawData[0])_
- [DefaultTo](https://ramdajs.com/docs/#defaultTo) -> Renvoie par default  un objet vide _(si le head retourne `undefined` ou `null`, c'est une sécuritée)_
- [Keys](https://ramdajs.com/docs/#keys) -> Retourne un tableau contenant les clés de l'objet
- [Map](https://ramdajs.com/docs/#map)(makecolumn) -> Applique pour chaque clé la fonction `makeColumn`

`makeColumn` Crée l'object un object à partir d'une clé

2020-10-12 17:19 UTC, maximenathan commented on config/locales/en.json
> +  "License": "License",
Je vais refaire une passe sur la traduction car c'est pas top :)

C'est probablement parceque l'api retourne `license` et je veux l'afficher en majuscule... solution rapide :)

2020-10-12 17:23 UTC, maximenathan commented
> Dans la story, le contenu des cases du header du tableau est aligné gauche tandis que le contenu des cellules de données est aligné à droite : je ne trouve pas ça très clair.
> ![image](https://user-images.githubusercontent.com/20704943/95558997-5fa35f80-0a17-11eb-8e9c-8dba510a5b8b.png)

C'est pas top en effet. Je vais modifier ca

2020-10-14 09:44 UTC, Clm-Roig commented on assets/js/react/components/common/Table/TableHead.jsx
> +  return pipe(head, defaultTo({}), keys, map(makeColumn))(rawData);
Oui je saisis tous les intérêts et j'ai lu la doc ^^ De toute tu peux laisser, question de goût / habitude comme tu dis. Je finirais ptêtre par y passer aussi !

2020-10-14 09:45 UTC, Clm-Roig commented on config/locales/en.json
> +  "License": "License",
Ah oui rapide mais vraiment pas top ahaha 
> Je vais refaire une passe sur la traduction car c'est pas top :)

ça marche !

2020-10-15 07:08 UTC, Clm-Roig commented
> Description de la PR mis à jours
> J'ai rebase & squash des commits pour avoir un historique plus propre
> 
> @Clm-Roig tu peux rebase la branche `feature/doc_to_validate_api` sur `rc` ? Il y a quelques conflict que je n'ai pas osé les résoudre

ça marche, je m'en occupe de suite

2020-10-15 13:14 UTC, Clm-Roig requested changes
C'est quasiment bon pour moi à part 2-3 remarques mineures :slightly_smiling_face: 
Reste à peaufiner le détail d'un document. Je rajoute une **moderatorPolicy** vite fait pour les fonctions de validation / process d'un document.

2020-10-15 13:14 UTC, Clm-Roig commented on assets/js/react/actions/ProcessDocuments.js
> +  const authToken = window.localStorage.getItem(identificationTokenName);
Pour s'identifier, Il faut utiliser **getAuthHTTPHeader()** désormais et le mettre dans les _requestOptions_ de fetch. Il y a un exemple dans **actions/Caver.js**

2020-10-15 13:14 UTC, Clm-Roig commented on assets/js/react/pages/DocumentDetails/index.jsx
> +            label: formatMessage({ id: 'Document father' }),
J'ai utilisé _**Parent document**_ jusqu'à maintenant si jamais tu veux rester consistant.

2020-10-15 13:14 UTC, Clm-Roig commented on assets/js/react/pages/DocumentDetails/index.jsx
> +            label: formatMessage({ id: 'Area' }),
J'ai utilisé _**Regions**_ jusqu'à maintenant si jamais tu veux rester consistant.

2020-10-15 13:14 UTC, Clm-Roig commented on assets/js/react/pages/DocumentDetails/index.jsx
> +            value: entities.entry,
**Entrance**, au lieu de **_entry_**. J'essaie de faire disparaître le terme entry de l'application, il n'est pas correct dans le contexte de Grottocenter.

2020-10-17 18:24 UTC, Clm-Roig approved these changes

2020-10-19 08:19 UTC, merged