[FEATURE][DocSubmission] Caver & Organization creation
GrottoCenter/Grottocenter3 pull request #376
Opened 2020-10-27 14:53 UTC by maximenathan

In Document submission, it's now possible to create a caver & organization (possible only if the user search first)

2020-11-01 09:23 UTC, Clm-Roig requested changes
J'ai rajouté un commit qui permet d'ajouter le nom d'une organization fraîchement créée à Elasticsearch, j'avais oublié l'attribut. 

J'ai repéré un petit bug à la création d'un caver. Quand on veut passer de l'input name à l'input surname avec Tab ça ne fonctionne pas : ça sélectionner le wrapper autour du 2ème input et pas l'input lui-même j'ai l'impression. 
Si tu arrives à corriger ça rapidement ce serait top, sinon pas grave.

C'est pas forcément évident que la flèche sur le côté (le `<ExpandMore>`) permet d'ajouter une entité : on le préciser dans le **helperText** des barres de recherche.

C'est cool sinon, beau boulot !

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/actions/CreateCaver.js
> +export const RESET_API_MESSAGES = 'RESET_API_MESSAGES';
ça me paraît inutilisé ici, peut-être un mauvais copié / collé depuis actions/Documents.js ?

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/actions/CreateCaver.js
> +    body: JSON.stringify({ name, surname, token: authToken }),
Le token n'a plus besoin d'être mis dans le body : il est dans les headers, c'est suffisant.

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/actions/CreateOrganization.js
> +export const RESET_API_MESSAGES = 'RESET_API_MESSAGES';
ça me paraît inutilisé ici, peut-être un mauvais copié / collé depuis actions/Documents.js ?

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/actions/CreateOrganization.js
> +    body: JSON.stringify({ name, token: authToken }),
Le token n'a plus besoin d'être mis dans le body : il est dans les headers, c'est suffisant.

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/features/Form/MultipleCaversSelect/CreateNewCaver.jsx
> +        label={formatMessage({ id: 'name' })}
A changer par :

`label={formatMessage({ id: 'Caver.Name' })} `

Majuscule + ce n'est pas juste 'name'. J'ai rajouté une clé de traduction Caver.Name pour, par exemple, en français on traduise ça "prénom" et pas "nom".

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/features/Form/MultipleCaversSelect/CreateNewCaver.jsx
> +        label={formatMessage({ id: 'surname' })}
Majuscule à surname :

`label={formatMessage({ id: 'Surname' })} `

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/features/Form/OrganizationAutoComplete/CreateNewOrganization.jsx
> +        label={formatMessage({ id: 'new organization' })}
Changer par : 

`label={formatMessage({ id: 'Name' })} `

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/reducers/GCReducer.jsx
> +  createOrganization,
A descendre d'une ligne pour respecter l'ordre alphabétique.

2020-11-01 09:23 UTC, Clm-Roig commented on assets/js/react/features/Form/OrganizationAutoComplete/index.jsx
> +const Index = ({
Je ne suis pas sûr de comprendre la nécessité de renommer le composant en **Index** : c'est voulu  de ta part ? ^^

2020-11-01 17:00 UTC, maximenathan commented on assets/js/react/features/Form/OrganizationAutoComplete/index.jsx
> +const Index = ({
C'est une modif de mon IDE :)

A renomer

2020-11-02 10:46 UTC, maximenathan commented
> J'ai rajouté un commit qui permet d'ajouter le nom d'une organization fraîchement créée à Elasticsearch, j'avais oublié l'attribut.
> 
> J'ai repéré un petit bug à la création d'un caver. Quand on veut passer de l'input name à l'input surname avec Tab ça ne fonctionne pas : ça sélectionner le wrapper autour du 2ème input et pas l'input lui-même j'ai l'impression.
> Si tu arrives à corriger ça rapidement ce serait top, sinon pas grave.
> 
> C'est pas forcément évident que la flèche sur le côté (le `<ExpandMore>`) permet d'ajouter une entité : on le préciser dans le **helperText** des barres de recherche.
> 
> C'est cool sinon, beau boulot !

Merci

L'erreur du focus s'était une mauvaise utilisation du `tabIndex` de ma part
C'est réglé

2020-11-02 20:13 UTC, Clm-Roig approved these changes

2020-11-02 20:13 UTC, Clm-Roig commented
> 
> Merci
> 
> L'erreur du focus s'était une mauvaise utilisation du `tabIndex` de ma part
> C'est réglé

Super, tout est ok, j'ai approuvé :smiley:

2020-11-03 09:07 UTC, merged