chore(mock): add mock database script
GrottoCenter/Grottocenter3 pull request #521
Opened 2021-03-12 00:25 UTC by bsoufflet

Also remove old dependencies to MySQL.
upgrade ORM version and sails-postgre

2021-03-12 00:26 UTC, bsoufflet commented
@ClemRz : Ce fichier SQL de Mock pourrait servir pour le docker compose pour avoir un BDD minimal sans dump complet.

2021-03-12 00:27 UTC, bsoufflet commented
@ClemRz @Clm-Roig : C'est une première version des données Mock qu'il faudra faire évoluer en fonction des cas que l'on veut tester depuis l'application lancé en local.

2021-03-12 09:11 UTC, Clm-Roig requested changes

2021-03-12 09:11 UTC, Clm-Roig commented on sql/mock_data.sql
> +	 (11,'Caver - edit all',NULL);
Je viens de merge la [PR qui modifie les droits](https://github.com/GrottoCenter/Grottocenter3/pull/519), il faut donc renommer 2 choses pour être en accord avec celle-ci : 
- **Bibliography** qui devient **Document**
- **all** qui devient **any**

2021-03-30 21:11 UTC, Clm-Roig commented
J'ai rajouté des données concernant les droits, histoire que ceux-ci soient cohérents avec ce qu'on a actuellement sur develop et master.

2021-03-31 08:06 UTC, Clm-Roig submitted a review, later dismissed

2021-04-04 21:26 UTC, merged