[CAVE API] Add create cave api route
GrottoCenter/Grottocenter3 pull request #531
Opened 2021-04-05 16:47 UTC by Clm-Roig

2021-04-10 09:52 UTC, Clm-Roig commented
![](https://github.trello.services/images/mini-trello-icon.png) [Créer une cavité](https://trello.com/c/ntnZgFiD/171-cr%C3%A9er-une-cavit%C3%A9)

2021-04-10 15:05 UTC, bsoufflet commented on api/controllers/CaveController.js
> +          author: req.token.id,
@Clm-Roig : Il ne manque pas le set du champ "name" ?

2021-04-10 15:07 UTC, bsoufflet requested changes

2021-04-10 15:07 UTC, bsoufflet commented on api/controllers/CaveController.js
> +          isMain: true,
@Clm-Roig  : Il ne manque pas le set du champ "name" ?

2021-04-11 15:24 UTC, Clm-Roig commented on api/controllers/CaveController.js
> +          isMain: true,
Oui effectivement, je sais pas pourquoi il a sauté. Je corrige ça demain quand je reprends le boulot.

2021-04-14 18:43 UTC, bsoufflet approved these changes

2021-04-14 18:55 UTC, Clm-Roig commented
Je pushe pour résoudre les conflits

2021-04-14 18:57 UTC, Clm-Roig commented
J'ai un bug à résoudre avant de merge : **_isDeleted_** non-reconnu (toujours cette histoire d'alias d'attribut du modèle), faut que je bascule en **_is_deleted_**.

2021-04-16 15:38 UTC, bsoufflet approved these changes

2021-04-16 19:51 UTC, merged