[ENTRANCE API] Add set entrance documents api route
GrottoCenter/Grottocenter3 pull request #545
Opened 2021-04-19 12:06 UTC by Clm-Roig

2021-05-04 10:06 UTC, bsoufflet commented on apiV1.yaml
> +  '/entrances/{entranceId}/documents':
@Clm-Roig : Ici on set tous les documents de l'entrance. Ne faudrait il pas une route (plus sur) qui permettrait d'ajouter un seul document ? 
Cette route ne peut elle pas servir à supprimer toutes les relations (ou bien tous sauf 1) avec les documents d'une entrance ? Et les relations ne sont pas historisées ce qui peut rendre difficile la reconstruction des relations en cas d'erreur (intentionnelle ou non ) non ?
Serait il possible de logger (peut etre dans une nouvelle table SQL) toutes les modifications aux relation (tables j_) pour pouvoir facilement les revert en cas de problème ?

2021-05-04 10:08 UTC, bsoufflet requested changes

2021-05-04 10:08 UTC, bsoufflet commented on apiV1.yaml
> +  '/entrances/{entranceId}/documents':
Quand on va utiliser cette route cela veut dire que l'on sera dépendant de la route qui récupère les documents d'une entrance. Et donc si la route de recuperation a une erreur on pourrait propager des suppressions involontaires de doc non ?

2021-05-04 10:36 UTC, Clm-Roig commented on apiV1.yaml
> +  '/entrances/{entranceId}/documents':
> Ici on set tous les documents de l'entrance. Ne faudrait il pas une route (plus sur) qui permettrait d'ajouter un seul document ?
> Cette route ne peut elle pas servir à supprimer toutes les relations (ou bien tous sauf 1) avec les documents d'une entrance ? 

Effectivement, j'avais pas pensé au cas d'usage de la suppression (involontaire). Je vais refaire cette route avec un PUT pour ajouter des documents uniquement et un DELETE pour supprimer un par un.

> Et les relations ne sont pas historisées ce qui peut rendre difficile la reconstruction des relations en cas d'erreur (intentionnelle ou non ) non ?
> Serait il possible de logger (peut etre dans une nouvelle table SQL) toutes les modifications aux relation (tables j_) pour pouvoir facilement les revert en cas de problème ?

Je trouve pas ça pas trop grave dans l'absolu. L'historisation de ces relations ne me semble pas indispensable. Après pourquoi pas, j'ai juste pas les connaissances appropriées en BD pour faire ça 😅

2021-05-04 21:57 UTC, bsoufflet commented on apiV1.yaml
> +  '/entrances/{entranceId}/documents':
On avait dans la base Mysql de GC2 une table T_warning qui stockait les valeurs avant leur changement. Cette table n'est plus nécessaire car toutes les tables T_ maintenant historisées mais nous pourrions avoir le memeconcept pour les changements sur les tables j_ .

Voici un exemple de data de la table T_warning :

|Id|Id_caver|Frame|Date|Warning|Comment|
|--|--------|-----|----|-------|-------|
|11216|2764||2021-05-04 20:28:47.0|Tracker : a new comment has been added :  by audelucievial.|IdLockedId_authorId_answeredId_reviewerId_lockerDate_inscriptionDate_reviewedDate_lockedId_entryId_exitRelevanceE_t_undergroundE_t_trailAestheticismCavingApproachTitleBodyAlert4093NO2764&nbsp;&nbsp;&nbsp;2021-05-04 20:28:47&nbsp;&nbsp;7520604&nbsp;30:00:00&nbsp;&nbsp;&nbsp;&nbsp;Description : Un porche d’environ 2m de haut sur 3,50m de large. Sur la droite du porche il y a un petit orifice permettant de laisser passer un humain (sans intérêt). En face, un ressaut d’un mètre 50, qui permet de remonter dans une petite salle avec une sortie sur la colline. 
|11215|2042||2021-05-04 20:16:14.0|Tracker : a new rigging has been added :  by JiPi82.|IdLockedId_authorId_reviewerId_lockerDate_inscriptionDate_reviewedDate_lockedRelevanceId_exitTitleObstaclesRopesAnchorsObservations1734NO2042&nbsp;&nbsp;2021-05-04 20:16:14&nbsp;&nbsp;4&nbsp;&nbsp;Main-courante et Vire&#124;;&#124;P15 (puits incliné)C50&#124;;&#124;C258 mousquetons&#124;;&#124;5 mousquetonsAmarrages nat. Prévoir Deenema en secours&#124;;&#124;Le puits est broché|

De manière très simple tous les update / delete / create sur les tables J_ pourrait provoquer un enregistrement dans une table d'historisation. Je vais voir pour le faire via trigger postgreSQL...

2021-05-06 11:00 UTC, Clm-Roig commented
@bsoufflet j'ai remplacé **setDocuments** par **addDocument** comme convenu. 
Je ferai une autre branche et PR pour removeDocument qui sera permis uniquement aux modérateurs. 

J'ai rajouté 2 droits dans la BD pour préciser tout ça : **link resource** (User) et **unlink resource** (Moderator).

2021-05-07 22:25 UTC, bsoufflet approved these changes

2021-05-08 07:36 UTC, merged