[HOME PAGE DYNAMIC NUMBERS] Fix number of Grottocenter users
GrottoCenter/Grottocenter3 pull request #556
Opened 2021-04-28 20:43 UTC by Clm-Roig

Fix #493

2021-05-07 22:32 UTC, bsoufflet requested changes

2021-05-07 22:32 UTC, bsoufflet commented on api/controllers/CaverController.js
> +    TCaver.count({ mail: { '!=': 'no@mail.no' } }).exec((err, found) => {
On a pas un moyen plus smart avec le schema SQL pour differentier les users de grottocenter de tous les cavers ?

Je me demande par exemple si le champ "activated" ou "login" ne serait pas mieux que de se baser sur l'email ?

2021-05-08 07:48 UTC, Clm-Roig commented on api/controllers/CaverController.js
> +    TCaver.count({ mail: { '!=': 'no@mail.no' } }).exec((err, found) => {
Dans l'état actuel des choses : 
"activated" => on n'a pas encore la validation d'un nouveau compte de prête hélas.
"login" => cet attribut n'est plus utilisé pour les inscriptions et pour l'authentification : je lui ai préféré l'email. Le login change d'un site à l'autre, c'est difficile de se souvenir de quel login va pour quel site (alors que le mail reste souvent le même).

Tout ça mérite une discussion à plusieurs je pense. J'avais dû prendre ces décisions seul pendant d'autres devs, il y a peut-être mieux à faire.

2021-05-12 05:23 UTC, urien commented on api/controllers/CaverController.js
> +    TCaver.count({ mail: { '!=': 'no@mail.no' } }).exec((err, found) => {
La solution de Clément fonctionne, une autre approche serait de compter le nombre de mels différents -1 (no@mail.no)

2021-05-12 14:15 UTC, Clm-Roig commented on api/controllers/CaverController.js
> +    TCaver.count({ mail: { '!=': 'no@mail.no' } }).exec((err, found) => {
Oui tu as raison @urien vu qu'on a des doublons de mails, ta solution est plus précise. 
Mais dans tous les cas, il faut nettoyer ces mails et interdire les dupplications de mail : dans ce cas-là, les deux se valent :slightly_smiling_face:

2021-05-14 08:57 UTC, Clm-Roig commented
J'ai changé la méthode de comptage : j'utilise le nombre de mails distinct - 1 comme suggéré par Frédéric.

2021-05-14 21:29 UTC, bsoufflet approved these changes

2021-05-15 09:40 UTC, merged