[CAVE MODEL] Drop not null massif constraint
GrottoCenter/Grottocenter3 pull request #565
Opened 2021-05-05 20:07 UTC by Clm-Roig

DB production has been changed

2021-05-05 23:04 UTC, bsoufflet requested changes

2021-05-05 23:04 UTC, bsoufflet commented on sql/0_tables.sql
> +	id_massif int4,
Il n'y a pas le h_cave à changer aussi ?

Tu t'occupes ensuite de lancer la requete SQL sur la base de prod au moment du deploy ?
ne faudrait il pas plutot faire comme avant un (ou plusieurs) fichiers SQL contenant toutes les query SQL appliqué sur la base de prod ?

2021-05-06 10:05 UTC, Clm-Roig commented on sql/0_tables.sql
> +	id_massif int4,
ça me paraît suffisant de toucher simplement au script **0_tables.sql** quand ce sont des petites modifications non ? 
J'ai oublié h_cave effectivement, je regarde ça. 
La BD de prod est déjà modifiée vu que ça n'affecte pas le fonctionnement de la prod.

2021-05-07 22:17 UTC, bsoufflet commented on sql/0_tables.sql
> +	id_massif int4,
ok

2021-05-07 22:18 UTC, bsoufflet approved these changes

2021-05-08 07:54 UTC, merged