[LOCATION API] Edit location api route
GrottoCenter/Grottocenter3 pull request #571
Opened 2021-05-11 16:56 UTC by Clm-Roig

Utilisateur => ne peut éditer que ses locations
Modérateur => peut éditer tous les locations

On ne peut éditer que le **body** d'une location, c'est bien ça ? @bsoufflet @urien 

(la relevance n'est pas encore gérée, comme sur les autres entités, il faudra y songer)

2021-05-11 20:11 UTC, bsoufflet commented
@Clm-Roig : Pour moi n'importe quel utilisateur connecté dois pouvoir modifier n'importe quel description / location.

@urien : Est-on d'accord que la personne qui édite une description existante a son nom qui est inscrit dans le champ id_author ?
Les précédents auteurs sont retrouvable via la table h_description c'est ca ?

Il y a un title pour description mais pas pour location ca me semble normal.

@urien : Ne devrait on pas se débarasser des date_reviewed et id_reviewer des tables t_description et t_location ?
@urien : La relevance est un ancien concept qui est obsolète et à supprimer non ?

2021-05-12 05:19 UTC, urien commented
Pour moi
Le créateur ou la derniere personne a faire une modification est id_auteur, les autres  sont retrouvés par la table h_
le titre pour la location existait sur la V2 et me semblait utile s'il est possible de faire plusieurs locations : accès 4x4, accès à pied, accès en télésiège, accès si on a la clé de la barrière.
A priori date_reviewed et id_reviewer ne serviront plus puisque les infos sont dans les tables h_ mais on peu attendre avant de les enlever
La relevance permettait de classer l'ordre des descriptions (ou des autres pavés). Cela me semble utile. Par exemple si on tronçonne la description d'une cavité : depuis l'entrée jusq'au carrefour, du carrefour à la salle, du carrefour au siphon.... L'ordre dans lequel on va les créer ne sera pas l'ordre dans lequel on souhaitera les voir apparaitre

2021-05-12 09:05 UTC, Clm-Roig commented
> 
> 
> @Clm-Roig : Pour moi n'importe quel utilisateur connecté dois pouvoir modifier n'importe quel description / location.
> 

Ça me paraît bizarre de pouvoir modifier ce qu'un autre utilisateur a dit. Pour moi, chaque utilisateur poste (et édite) ce qu'il désire. Contrairement au nom qui a une valeur "officielle / définie / exacte", une location ou une description c'est quelque chose de personnel et qui sera forcément différent d'un utilisateur. 

Après, c'est la relevance qui peut intervenir pour classer les descriptions / locations pertinentes ou non.

2021-05-12 10:46 UTC, urien commented
La description et la location sont des textes partagés que chacun peut améliorer ou corriger. Comme l'historique, l'équipement.
Le seul truc personnel que les autres ne doivent pas pouvoir éditer ce sont les commentaires. 
Je pense comme toi que la relevance sert a ordonner les contributions

2021-05-12 10:58 UTC, Clm-Roig commented
Ok comme vous voulez, c'est juste une question de philosophie et de points de vue après ^^ J'attends la confirmation de @bsoufflet pour modifier et merger 🙂

2021-05-13 08:14 UTC, bsoufflet commented
Je confirme ce que Frédéric dit. On est dans un wiki, le but n'est donc pas d'avoir 1 description par utilisateur mais bien que les utilisateurs travaillent ensemble pour améliorer les textes existants.
De la meme manière on ne veut pas voir 50 articles sur le meme sujet sur Wikipédia par 50 utilisateurs différents ;)
La seule exception est en effet le commentaire qui est un texte bien personnel à l'utilisateur (qu'un modérateur ou admin peut tout de meme supprimer ou éditer pour le censurer si besoin)

2021-05-13 08:29 UTC, bsoufflet commented
@urien @Clm-Roig : Sinon ok pour rajouter un title sur location
pour les colonnes reviewer et autres on verra plus tard pour faire le ménage mais pour l'instant on ne les gère pas dans les API.

Pour la relevance ne faudrait il pas mettre en place une gestion minimaliste pour l'instant juste pour gérer l'ordre. Du type relevance = count des location existante + 1 ?

2021-05-13 08:31 UTC, bsoufflet requested changes
Appliquer ce que l'on vient de dire en discussion :)

2021-05-13 08:31 UTC, urien commented
Oui c'est une bonne idée pour pouvoir gérer cette question du côté Front

2021-05-13 08:39 UTC, bsoufflet commented
@urien @Clm-Roig : La solution la plus simple pour gérer l'ordre des Locations / descriptions serait de ne pas laisser le front gérer la relevance mais d'avoir une valeur par défaut set par le back au moment de la création qui serait : 
`relevance = maxRelevanceFound + 1`
Ensuite il faudrait 2 petites routes `moveUp` et `moveDown` qui s'occuperait coté back d'inverser les relevances entre les 2 éléments.

2021-05-13 08:50 UTC, urien commented
Oui, c'est une solution élégante

2021-05-14 07:56 UTC, Clm-Roig commented
J'ai créé une issue pour la relevance : https://github.com/GrottoCenter/Grottocenter3/issues/574

J'ai ajouté une colonne "title" à une location, ce sera pratique effectivement.

J'ai modifié les droits pour que tout le monde puisse éditer une location.

2021-05-14 08:03 UTC, Clm-Roig commented
Une question subsiste : quelle valeur mettre dans la colonne **title** pour les précédentes données ? 
Je pensais contraindre à "not null" mais ce n'est pas possible... A moins de mettre une valeur par défaut ou une chaîne de caractères vide :confused:

2021-05-14 21:22 UTC, bsoufflet commented
ca me va si le title n'est pas obligatoire. Pour des petites cavités il y a parfois que 1 seul location et le titre n'est donc pas necessaire dans ce cas.

2021-05-14 21:23 UTC, bsoufflet requested changes

2021-05-14 21:23 UTC, bsoufflet commented on api/models/TLocation.js
> +      allowNull: false,
true ?

2021-05-15 20:52 UTC, bsoufflet commented on sql/0_tables.sql
> +	title varchar(300) NOT NULL,
Not NULL du coup ici ?

2021-05-15 20:53 UTC, bsoufflet commented on sql/0_tables.sql
> +	title varchar(300) NOT NULL,
@Clm-Roig

2021-05-15 20:53 UTC, bsoufflet approved these changes

2021-05-16 17:28 UTC, Clm-Roig commented on sql/0_tables.sql
> +	title varchar(300) NOT NULL,
c'est modifié merci !

2021-05-16 17:30 UTC, merged