[DESCRIPTION API] Create description api route
GrottoCenter/Grottocenter3 pull request #572
Opened 2021-05-11 19:56 UTC by Clm-Roig

2021-05-11 20:13 UTC, bsoufflet commented
@urien @Clm-Roig : Mes remarques sur la PR pour la location est également valable ici. Je fini la review lorsque l'on a éclaircie cela :)

2021-05-13 08:32 UTC, bsoufflet requested changes
Nos remarques et commentaires sur LOCATION s'appliquent ici également

2021-05-14 08:22 UTC, Clm-Roig commented
> Nos remarques et commentaires sur LOCATION s'appliquent ici également

Hum que faut-il appliquer ici ? La création est déjà permise à tous les utilisateurs et la relevance sera gérée dans une autre PR (l'issue est ici => https://github.com/GrottoCenter/Grottocenter3/issues/574)

2021-05-14 21:27 UTC, bsoufflet approved these changes

2021-05-15 09:26 UTC, merged