[NAME API] Edit isMain api route
GrottoCenter/Grottocenter3 pull request #573
Opened 2021-05-12 14:54 UTC by Clm-Roig

- N'importe qui peut éditer le *isMain* d'un name.
- S'il veut le setter à `true`, tous les autres names se référant à la même entité (cave, entrance, massif, grotto, point) voient leur isMain passer à `false`. Cela permet de préserver l'unicité du isMain pour une entité donnée.

2021-05-13 08:09 UTC, bsoufflet requested changes

2021-05-13 08:09 UTC, bsoufflet commented on api/controllers/NameController.js
> +  updateIsMain: async (req, res, converter) => {
Vu que l'on ne veut pas autoriser de set IsMain à false (mais que de mettre le isMain sur un autre nom, ne devrions nous pas changer cette méthode de `updateIsMain` à `setAsMain`par exemple ?
Il n'y aurais alors plus besoin de passer un booléen à true ou false.
On ne gèrerai que le cas où l'on met un nom à main=true et donc on passe tous les autres à main=false.

2021-05-13 08:09 UTC, bsoufflet commented on api/controllers/NameController.js
>        .populate('grotto')
Dans la route update au dessus : 
- il faudrait autoriser tous les users à update un name
- il ne faudrait pas laisser changer le isMain via cette route udpate afin de n'avoir la logique du isMain que à un seul endroit non ?

2021-05-13 08:09 UTC, bsoufflet commented on api/controllers/NameController.js
> +  },
Tu feras une route de delete de name pour les admin plus tard ?
Dans cette route il faudra avoir un peu de logique pour interdire le delete d'un nom qui a isMain à true

2021-05-14 08:15 UTC, Clm-Roig commented on api/controllers/NameController.js
> +  },
Pour les modérateurs non plutôt ? Oui pour le reste effectivement

2021-05-14 21:24 UTC, bsoufflet commented on api/controllers/NameController.js
> +  },
oui admin et moderateur :)

2021-05-14 21:25 UTC, bsoufflet approved these changes

2021-05-15 09:25 UTC, merged