fix(search): add special char to ignore
GrottoCenter/Grottocenter3 pull request #598
Opened 2021-06-16 14:37 UTC by AxelCanton

- Add french quote mark to the special characters we must ignore
- Remove the last dot of a search query, if there is any. If you add it, even if the field (title or description) possesses such dot at the end, it couldn't be found.

2021-06-16 14:47 UTC, urien commented
Super !

2021-06-18 09:27 UTC, Clm-Roig requested changes

2021-06-18 09:27 UTC, Clm-Roig commented on api/services/ElasticsearchService.js
> +    }
C'est bon pour moi, juste 2 petites améliorations de mise en forme :

```js
sourceString.replace(/[`~!@#$%^&*()_|+\-=?;:",<>«»\{\}\[\]\/\\]/gi, ' ');  // <---- le point virgule à la fin
sourceString = sourceString[sourceString.length-1] === '.' ? sourceString.slice(0, -1) : sourceString; // <---- if en une ligne

```

2021-06-18 10:29 UTC, Clm-Roig approved these changes

2021-06-22 20:19 UTC, merged