Feature/import csv
GrottoCenter/Grottocenter3 pull request #601
Opened 2021-07-13 12:01 UTC by AxelCanton

- Add components to import csv files
- new dedicated controller for imported files
- some refactoring for grotto, caver, cave, entrance, document controllers
- new migration file

To access the import module : new button in the dashboard for users.

2021-07-29 22:36 UTC, bsoufflet requested changes

2021-07-29 22:36 UTC, bsoufflet commented on apiV1.yaml
> +  '/importCsv/checkRows':
Le standard pour les API REST est d'utiliser hyphen plutot que camelCase. Je sais que c'est clean actuellement dans notre API car chaque dev a fait ce qu'il voulait malheureusement...
De plus le fait que la route d'import CSV soit la meme pour importer du document et de l'entrance ne me semble pas l'idéal si on veut respecter les conventions des API REST...
Il faudrait plutot avoir POST /documents/csv/check-rows et /entrances/csv/check-rows meme si derrière tu utilises 1 seul service d'import csv :)

2021-07-29 22:36 UTC, bsoufflet commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +      /,(?![^"]*"(?:(?:[^"]*"){2})*[^"]*$)/,
Les expressions régulières (surtout compliquées) sont pour moi à éviter le plus possible dans du code source car elle sont compliquées à relire, à comprendre et à debugger...

2021-07-29 22:36 UTC, bsoufflet commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +    const dataStringLines = dataString.split(/\r\n|\n/);
Ca semble etre un parsing ultra manuel du CSV. Il n'y avait pas moyen d'utiliser une librairie existante pour simplifier et alleger notre code source ?
https://www.npmjs.com/package/react-csv-reader

2021-07-29 22:36 UTC, bsoufflet commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +const CSVDataValidator = ({ selectedFile, errorHandler }) => {
Le système supporte t'il plusieurs delimiter ? En effet un tableur US va generer des CSV avec la virgule en separateur alors que certains tableur francais vont generer les CSV avec du point-virgule ou de la tabulation par défaut. IL est ensuite difficile pour des utilisateurs non expert de faire le changement de l'un vers l'autre si nous ne supportons que l'un des delimiters. Certains lib CSV ont un detection automatique du delimiter et du type de saut de ligne (CRLF vs LF)...

2021-07-29 22:36 UTC, bsoufflet commented on assets/js/react/components/common/ImportCSV/Helper.js
> +    /([12][0-9]{3})-(0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01])|([12][0-9]{3}-(0[469]|11)-(0[1-9]|[12][0-9]|30))|([12][0-9]{3})-(02)-(0[1-9]|1[0-9]|2[0-8])|(([12][0-9](04|08|[2468][048]|[13579][26]))|2
Un petit commentaire expliquant cette regex est necessaire...

2021-07-29 22:37 UTC, bsoufflet commented
@maximenathan : Je viens de faire une première review mais pourrais tu regarder plus en profondeur la partie front ?

2021-07-31 10:30 UTC, Clm-Roig requested changes
J'ai fait une première passe sur tout ce qui concerne la base de données. Il faut bien penser à répercuter les modifications des modèles dans les fichiers sql ainsi que mettre à jour la prod pour que ça fonctionne. 

On peut mettre à jour la prod dès maintenant si jamais on ne fait qu'ajouter des colonnes et/ou relâcher des contraintes (ex : le name de t_name qui passe de 100 à 200 caractères). Il me faudrait juste la requête SQL appropriée (et testée en local) pour que je fasse la mise à jour :slightly_smiling_face:

2021-07-31 10:30 UTC, Clm-Roig commented on sql/2021_07_09_import_csv_columns.sql
> +UPDATE t_type SET url = 'http://id.loc.gov/vocabulary/marcgt/map' WHERE id = 19;
https plutôt que http ?

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TType.js
> +    url: {
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TDocument.js
> +
à répercuter sur mock_data.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TDocument.js
> +
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TEntrance.js
> +
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TGrotto.js
> +    },
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/JDocumentGrottoAuthor.js
> +};
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 10:30 UTC, Clm-Roig commented on api/models/TName.js
> +      maxLength: 200,
à répercuter sur sql/mock_data.sql et sql/0_tables.sql

2021-07-31 11:54 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/ImportKarstlinkInfo.jsx
> +        <div>
Avec une carte comme container principal, on se retrouve avec une carte sur une carte... Je trouve pas ça très clair visuellement et c'est pas recommandé par Material Design. 

![card on card](https://user-images.githubusercontent.com/20704943/127739086-c203237d-d731-43b2-9abe-34fd4b358daa.png)

Un simple séparateur \<hr /\> comme sur [l'ajout de documents](beta.grottocenter.org/ui/documents/add)) suffirait à détacher le texte des flèches "Précédent" et "Suivant". A voir aussi pour mettre ce texte au-dessus, comme sur l'ajout de documents également.

![ajout doc](https://user-images.githubusercontent.com/20704943/127739089-adf3a36c-7f12-4f4d-915c-4e70b0f633b0.png)

2021-07-31 11:58 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step2.jsx
> +          id: 'Selected files',
**Selected file** au singulier vu qu'on ne peut mettre qu'un seul fichier

2021-07-31 12:05 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/ImportErrorBlock.jsx
> +    marginBottom: '0.2rem',
Utiliser `marginBottom: ${({ theme }) => theme.spacing(1)}px;` 
A terme ce serait bien de tout passer en rem j'imagine (?). Mais pour l'instant on essaie de rester cohérent sur le theme.spacing et px.

2021-07-31 12:08 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/ImportContainer.jsx
> +          <Typography variant="h6">
```jsx
<Typography variant="h1">
```

h1 au lieu de h6 car il s'agit du titre de la page.

2021-07-31 12:12 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/Helper.js
> +    accepted: '',
Je n'ai pas trouvé à quoi servait le champ `accepted` dans tout le code...

2021-07-31 12:15 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +                    importErrors[columnName] = 'INVALID_DATE_FORMAT';
Utiliser le errorsDictionary dans le Helper plutôt.

2021-07-31 12:15 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +                      importErrors[columnName] = 'DATE_IN_FUTURE';
Utiliser le errorsDictionary dans le Helper plutôt.

2021-07-31 12:15 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +                      importErrors[columnName] = 'MODIFIED_BEFORE_CREATED';
Utiliser le errorsDictionary dans le Helper plutôt (d'ailleurs cette erreur n'est pas répertoriée, il faudrait l'ajouter au dictionnaire)

2021-07-31 12:26 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +                  }
Toute cette section-là pourrait aller dans `dateChecker()` je pense, ce serait plus clair.

2021-07-31 12:28 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/Helper.js
> +  DATE_IN_FUTURE: 'the date entered is later than the current date',
clé duppliquée

2021-07-31 12:28 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/Helper.js
> +  DATE_BEFORE_CREATED:
Clé déjà présente dans le dictionnaire

2021-07-31 12:34 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step4.jsx
> +const useStyles = makeStyles({
Utiliser `padding: ${({ theme }) => theme.spacing(1)}px;` dès qu'il y a du padding ou du margin.

2021-07-31 12:36 UTC, Clm-Roig commented on assets/js/react/components/common/ImportCSV/types.js
> +  { id: 2, name: 'File completion', isValid: false },
**File Completion** avec une majuscule à Completion histoire d'être cohérent avec les autres titres.

2021-08-02 22:29 UTC, maximenathan commented on api/controllers/ImportCsvController.js
> +  if (url.includes('art', 'article')) return 18;
l faudrait des Enums pour mieux comprendre le return

2021-08-06 07:59 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +function usePrevious(value) {
Nouveau hook à rajouter dans le dossier "Hooks" 
C'est assez générique pour être utiliser partout

2021-08-06 07:59 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +  });
Il ne faudrait pas mettre en dep `value` ?

2021-08-06 08:02 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +  const [validator] = React.useState(
Si `validator` n'est jamais update, autant juste déclarer une constante sans `useState`

2021-08-06 08:10 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +    const dataStringLines = dataString.split(/\r\n|\n/);
Il doit y avoir d'autres librairies comme ici https://github.com/Bunlong/react-papaparse

Avant de choisir une nouvelle dep il faut:
- Répond au use case
- Nombre de star sur github / download sur npm
- Toujours maintenu


Ca semble être le cas de `react-csv-reader` & `react-papaparse`

2021-08-06 08:15 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +      /,(?![^"]*"(?:(?:[^"]*"){2})*[^"]*$)/,
Oui c'est pas lisible. Si on a pas le choix alors:
- Faire une fonction (avec un nom explicite)
- Rajouter des tests unitaire (même si c'est que des [snapshots](https://jestjs.io/docs/snapshot-testing) avec plusieurs scénarios)

Les tests unitaires servent alors de documentation et facilitent la refactorisation

2021-08-06 08:29 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +            for (let j = 0; j < validatorArray.length; j += 1) {
A voir si c'est toujours utile en utilisant une librairie pour le csv

L'enchainement de `if` `else` `for` nesté rend le code difficile à lire. La norme est de 3/4 max
Il faut pouvoir lire le code sans savoir de quoi il s'agit et le comprendre.

2021-08-06 08:31 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/CSVDataValidator.jsx
> +  useEffect(() => {
Pour un peu gagner en lisibilité on tu peux faire un "hook custom" => c'est la même chose mais tu donnes un nom explicite au hook, ce qui permet de comprendre facilement à quoi il sert

2021-08-06 08:33 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/Helper.js
> +    /([12][0-9]{3})-(0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01])|([12][0-9]{3}-(0[469]|11)-(0[1-9]|[12][0-9]|30))|([12][0-9]{3})-(02)-(0[1-9]|1[0-9]|2[0-8])|(([12][0-9](04|08|[2468][048]|[13579][26]))|2
Un minimum quelques tests en cas de refactorisation

2021-08-06 08:33 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportContainer.jsx
> +  const [isNextStepDisabled, setIsNextStepDisabled] = React.useState(true);
Hook "useBoolean"

2021-08-06 08:35 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportContainer.jsx
> +  const handleStepNext = () => {
dans un `useCallback` ?

2021-08-06 08:35 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportContainer.jsx
> +  const handleStepBack = () => {
https://github.com/GrottoCenter/Grottocenter3/pull/601/files#r684055146

2021-08-06 08:41 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportContainer.jsx
> +  const LinearProgress = styled(MuiLinearProgress)`
A sortir du composant (comme dans d'autres composant comme `components/common/AppBar/index.jsx` )

2021-08-06 08:43 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportErrorBlock.jsx
> +      {Object.keys(errors).length !== 0 &&
Je pense que ça mérite de déclarer une variable `const errorKeys` :)

2021-08-06 09:03 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step4.jsx
> +  const wontBeCreatedData = () => {
C'est un composant React, A nommer avec une Majuscule. Ca peut aussi être sorti dans un autre fichier pour gagner en lisibilité

2021-08-06 09:05 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step4.jsx
> +  const errorMessages = () => {
https://github.com/GrottoCenter/Grottocenter3/pull/601/files#r684076616

Quand c'est possible éviter les mutations, React n'aime pas.
Ici c'est dans un scope bien définit donc ça peut rester

2021-08-06 09:06 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step4.jsx
> +      {importCsv.resultCheck.wontBeCreated &&
Avoir les conditions dans une variable avec un nom explicite ?

2021-08-06 09:08 UTC, maximenathan commented on assets/js/react/components/common/ImportCSV/Provider.js
> +  const [isFormValid, setIsFormValid] = useState(false);
useBoolean

2021-08-06 18:17 UTC, AxelCanton commented
@Clm-Roig Normalement le fichier de migration (dans le dossier sql) est exécuté après la création des tables et leur remplissable, donc je devrais pas avoir à modifier ces fichiers (dans les faits ça marche pas encore parce que j'ai pas réussi à configurer docker malgré la documentation que m'a envoyé Benjamin).
Pour les attributs qui sont pas concernés par le fichier de migration, ce sont des colonnes qui existaient déjà dans la bdd mais qui n'avaient pas été ajoutées dans le model.

2021-08-06 19:08 UTC, Clm-Roig commented
> @Clm-Roig Normalement le fichier de migration (dans le dossier sql) est exécuté après la création des tables et leur remplissable, donc je devrais pas avoir à modifier ces fichiers (dans les faits ça marche pas encore parce que j'ai pas réussi à configurer docker malgré la documentation que m'a envoyé Benjamin).

Je ne suis pas sûr de comprendre... Pour moi on n'a besoin que des fichiers dans /sql pour créer une BD from scratch et les fichiers sont exécutés dans l'ordre alphabétique. Comment tu fais pour remplir ta BD autrement qu'avec mock_data si jamais on ne te fournit pas de dump ? (le but étant justement d'arrêter de fournir des dumps mais plutôt de se baser sur mock_data.sql pour construire un jeu de données de test le plus complete possible).

2021-08-06 19:28 UTC, AxelCanton commented on sql/2021_07_09_import_csv_columns.sql
> +UPDATE t_type SET url = 'http://id.loc.gov/vocabulary/marcgt/map' WHERE id = 19;
j'ai confirmé avec Frédéric les liens sont bons.

2021-08-06 19:41 UTC, AxelCanton commented
Les fichiers de migrations sont bien dans sql, et correspondrait aux versions consécutives de la bdd et de ces mises à jour. Après que les fichiers de migrations soient exécutés, on aurait la version finale de la bdd from scratch.

Par contre j'avoue que les update sur les types ne correspond à ce que je viens de dire si les types ne font même pas partie du mock de base..

Il faudrait demander à @bsoufflet pour confirmation, c'est lui qui m'a expliqué comment faire et j'ai pas assez d'expérience pour savoir si c'est la norme de faire comme ça.

2021-08-07 22:57 UTC, bsoufflet commented
> Les fichiers de migrations sont bien dans sql, et correspondrait aux versions consécutives de la bdd et de ces mises à jour. Après que les fichiers de migrations soient exécutés, on aurait la version finale de la bdd from scratch.
> 
> Par contre j'avoue que les update sur les types ne correspond à ce que je viens de dire si les types ne font même pas partie du mock de base..
> 
> Il faudrait demander à @bsoufflet pour confirmation, c'est lui qui m'a expliqué comment faire et j'ai pas assez d'expérience pour savoir si c'est la norme de faire comme ça.

@AxelCanton @Clm-Roig : Ce que j'ai proposé à Axel c'est de faire des scripts SQL (nommer `20210831_mychange.sql`) pour toutes nouvelles modifications du schema plutot que de modifier les fichiers initiaux de creation des tables (`0_xxx.sql`). C'est ensuite ce fichier SQL qui doit etre exécuté en production. On a donc un historique des fichiers qui ont été joué au fur et à mesure sur la base de production.
Ensuite pour setup la base de mock de dev il faut faire en sorte que le container docker de postgre va bien jouer les fichiers SQL dans le bon ordre. C'est à dire initialisation (0_) puis les fichiers sql de modification du schema avec le nom commencant par la date, puis en dernier la donnée mock pour remplir cette base de dev.
Cela demande donc bien comme le dit @Clm-Roig  de modifier le fichier de mock pour y ajouter les nouvelles colonnes ou bien y ajouter de nouveaux exemples important à avoir pour les tests de dev...

Je suis plus clair ?

2021-08-08 12:52 UTC, AxelCanton commented
C'est clair pour moi, par contre j'ai mis des updates dans mon fichier de migration qui doivent être exécutés en prod, mais certainement pas avant que a bdd soient remplies. Le mieux serait de les enlever du fichier et de les exécuter à la main ?

2021-08-08 21:30 UTC, bsoufflet commented
> C'est clair pour moi, par contre j'ai mis des updates dans mon fichier de migration qui doivent être exécutés en prod, mais certainement pas avant que a bdd soient remplies. Le mieux serait de les enlever du fichier et de les exécuter à la main ?

Peut tu me préciser un peu plus ?
L"objectif du fichier de migration SQL est bien double : 
- pour la prod il permet d’historiser toutes les modifications et migrations SQL exécutés sur la base de production. Sachant que dans le cas de la production le script SQL est actuellement à jouer manuellement par un admin car il n'y a pas d'automatisation via l'intégration continue
-  pour le dev le fichier vient en complément des fichiers initiaux 0_xxx.sql et des fichier de migration précédent (chronologiquement si ils existent) et il permet de construire une base grottocenter à jour et équivalement à la prod mais vide. Ce fichier devrait à terme etre jouer automatiquement par le container docker à la création... Le fichier de données mock arrive en dernier pour remplir cette base. Il faut donc que le fichier mock contiennent des data compatible avec le tout dernier schema.

2021-08-09 14:32 UTC, AxelCanton commented
Si les fichiers de migrations s'exécutent avant le fichier mock les requêtes suivantes ne feront rien : 
UPDATE t_type SET url = 'http://purl.org/dc/dcmitype/Collection' WHERE id = 1;
UPDATE t_type SET url = 'http://purl.org/dc/dcmitype/Dataset' WHERE id = 2;
...

Ils faudrait qu'elles s'exécutent après le mock pour que ça ait du sens. Il faudrait plus ou moins différencier les fichier de migrations qui agissent sur les colonnes de ceux qui agissent sur les lignes.

2021-08-09 17:14 UTC, AxelCanton commented on assets/js/react/components/common/ImportCSV/ImportSteps/Step4.jsx
> +const useStyles = makeStyles({
Ca ne marche pas comme avec moi. D'ailleurs spacing est un tableau dans le theme c'est normal de l'appeler comme ça du coup ?
J'ai juste écrit ça dans makeStyles : 
bottomButton: {
    margin: `${({ theme }) => theme.spacing(4)}px`,
  },

2021-08-09 21:59 UTC, bsoufflet commented
> Si les fichiers de migrations s'exécutent avant le fichier mock les requêtes suivantes ne feront rien :
> UPDATE t_type SET url = 'http://purl.org/dc/dcmitype/Collection' WHERE id = 1;
> UPDATE t_type SET url = 'http://purl.org/dc/dcmitype/Dataset' WHERE id = 2;
> ...
> 
> Ils faudrait qu'elles s'exécutent après le mock pour que ça ait du sens. Il faudrait plus ou moins différencier les fichier de migrations qui agissent sur les colonnes de ceux qui agissent sur les lignes.

Non, ca ne pose pas de problème que ces requetes ne fasse rien dans le cas de la base de dev pour les tests.
Ces requetes serviront bien pour la prod et reste inutile pour le dev car c'est le fichier Mock qui doit contenir des data à jour tel que l'on souhaite avoir pour les tests de dev.
Donc si tu veux avoir `http://purl.org/dc/dcmitype/Collection` dans `t_type` pour l'ID 1 sur ta base de test, tu update le fichier de mock pour mettre la bonne valeur ;)
On peut en discuter si besoin !

2021-08-12 22:51 UTC, bsoufflet requested changes
@AxelCanton : Ca me va mais il faut absolument faire un nettoyage des commits avant de merge cette feature. 62 commits c'est beaucoup trop pour une fonctionnalité comme celle-ci... Il faudrait maximum 10 commits je pense...
A toi de jouer du `git rebase -i` pour réduire cela ;)

2021-08-12 22:53 UTC, bsoufflet commented
@Clm-Roig : Je pourrais te laisser deploy cette feature lorsque @AxelCanton aura nettoyé les commits ?
Il faudrait faire le merge sur develop (via git-flow) puis le merge sur master avec le tag :)

2021-08-12 23:30 UTC, Clm-Roig commented
> 
> 
> @Clm-Roig : Je pourrais te laisser deploy cette feature lorsque @AxelCanton aura nettoyé les commits ?
> Il faudrait faire le merge sur develop (via git-flow) puis le merge sur master avec le tag :)

Oui pas de souci, je ne pourrai juste pas m'en occuper entre le 21 et le 28 août

2021-08-13 10:52 UTC, AxelCanton commented
@Clm-Roig Pour les changements du mock je les ai pas faites. Pour les 2 nouvelles colonnes, ce n'est pas important elles seront à null de base. Le seul petit problème est la colonne url de t_type. Mais comme je n'ai pas réussi à faire en sorte que le fichier de migration (qui crée la colonne) soit exécuté par docker, ça lèvera une erreur si je remplis le mock. En soit c'est pas très grave c'est spécifique à l'import.

Par contre le fichier de migration en lui-même fait une erreur après la commande docker-compose up, il faut enlever le fichier, exécuté le commande, puis exécuté le script à part.

2021-09-05 14:45 UTC, Clm-Roig commented on sql/mock_data.sql
>  	 (6,'user6','welcome1',true,'0',false,404,406,'user',NULL,'My Name','user6@mail.no',true,'2008-07-28 16:18:16.000','2019-12-14 12:19:01.000',true,false,30,7,'fra');
Il faut une virgule à la fin plutôt qu'un point-virgule

2021-09-05 14:50 UTC, Clm-Roig commented on assets/js/react/components/appli/ImportCSV/ImportSteps/Step4.jsx
> +          <GreenTypography>
Je trouve ça déroutant que ce soit en vert : j'ai cru que l'import était terminé avec succès . 
Tu peux l'écrire en orange (couleur 'secondary' dans le thème du site) je pense !

2021-09-05 14:53 UTC, Clm-Roig commented on assets/js/react/components/appli/ImportCSV/ImportSteps/Step4.jsx
> +import ImportExportIcon from '@material-ui/icons/ImportExport';
La double flèche de ImportExport est étrange pour un upload. J'utiliserais Publish plutôt :
![image](https://user-images.githubusercontent.com/20704943/132131248-f43e60dc-3936-4d4a-a96d-62647c86fde5.png)

2021-09-05 15:02 UTC, Clm-Roig commented on api/helpers/CsvHelpers/get-author.js
> +    // if(esRes.hits.total.value === 0) {
Pourquoi ce code est commenté ?

2021-09-05 15:02 UTC, Clm-Roig commented on api/helpers/CsvHelpers/get-author.js
> +      //  authorId = esRes.hits.hits[0]['_source'].id;
Pourquoi ce code est commenté ?

2021-09-05 15:03 UTC, Clm-Roig commented on api/helpers/CsvHelpers/get-creator.js
> +    //       const caversArray = result.hits.hits;
Pourquoi ce code est commenté ?

2021-09-05 15:03 UTC, Clm-Roig commented on api/helpers/CsvHelpers/get-creator.js
> +        // caver = caversArray[0]['_source'];
Pourquoi ce code est commenté ?

2021-09-05 15:05 UTC, Clm-Roig commented on api/services/CaveService.js
> +   * @param {Object} authorId the id of the author
Plutôt 
`    * @param {String} ...` 
non ?

2021-09-05 15:07 UTC, Clm-Roig commented on apiV1.yaml
> +          description: Successful operation. Returns the data which are not duplicates. For those which are indeed dupicates, returns the line concerned in the csv.
dupicates => duplicates

2021-09-05 15:13 UTC, Clm-Roig commented
A propos de `selectedType` côté front qui vaut 1 ou 0 selon si on importe des entrées ou des documents : ce serait bien d'utiliser des constantes placées dans un fichier à part, fichier qui serait alors importé à chaque fois qu'on a besoin de vérifier la valeur de selectedType.

2021-09-12 19:51 UTC, AxelCanton commented on api/services/CaveService.js
> +   * @param {Object} authorId the id of the author
J'ai oublié de l'enlever ça n'y est même plus en fait.

2021-09-14 15:08 UTC, Clm-Roig approved these changes

2021-09-22 19:31 UTC, bsoufflet approved these changes

2021-09-26 13:40 UTC, merged