[DOC] Swagger yaml endpoint
GrottoCenter/Grottocenter3 pull request #652
Opened 2021-11-08 13:11 UTC by Clm-Roig

Fix #651

2021-11-10 23:26 UTC, bsoufflet requested changes

2021-11-10 23:26 UTC, bsoufflet commented on api/controllers/SwaggerController.js
> +      'apiV1.yaml',
si le fichier est renommé de apiV1.yaml en swagger.yaml ne faudrait il pas changer ici ?

2021-11-10 23:26 UTC, bsoufflet commented on api/controllers/SwaggerController.js
> +      'apiV1.yaml',
Aussi il me semble plus logique de laisser le v1 dans le nom du fichier yaml qui est à la racine du projet. Car le jour où on aura une v2 ce sera plus facile que de devoir renommer swagger.yaml en swaggerV1.yaml par exemple...

2021-11-13 14:02 UTC, Clm-Roig commented on api/controllers/SwaggerController.js
> +      'apiV1.yaml',
Sinon on pourrait mettre le fichier swaggerV1.yaml dans le dossier v1 des controllers ? Et on aurait le `controllersv1/SwaggerController` qui le renverrait (pareil pour v2, v3...). 

Quant à `controllers/SwaggerController`, il utiliserait la dernière version disponible.

2021-11-13 14:14 UTC, Clm-Roig commented on api/controllers/SwaggerController.js
> +      'apiV1.yaml',
Ah bah non Sails ne veut pas de .yaml dans le dossier /controllers... Je pensais les mettre dans `/assets`

2021-11-13 14:21 UTC, Clm-Roig commented on api/controllers/SwaggerController.js
> +      'apiV1.yaml',
J'ai push avec swaggerV1.yaml dans /assets et avec une meilleure gestion de l'erreur.

2021-11-14 22:20 UTC, bsoufflet approved these changes

2021-11-15 09:12 UTC, merged