Feature/handle duplicate
GrottoCenter/Grottocenter3 pull request #708
Opened 2022-01-16 17:30 UTC by AxelCanton

Nouvelles tables et leurs controllers : 
- t_duplicate_document
- t_duplicate_entrance

Nouvelle routes sur t_document et t_entrance : permet de mettre à jour une entité avec des entités liées pas encore créées (descriptions, names..).

2022-01-18 09:19 UTC, Clm-Roig requested changes
Je n'ai pas fait de review détaillé de DuplicatesEntranceController, ce sont les mêmes commentaires que sur DuplicatesDocumentController. 

ça manque un peu de commentaires et il manque la doc des routes dans `swaggerV1.yaml`. 

Le nom des routes et controlers n'est pas très juste en anglais. _Duplicate_ est un nom donc (même chose pour entrance à chaque fois) :

TDuplicateDocument => TDocumentDuplicate 
DuplicatesDocumentController => DocumentDuplicateController (les contrôleurs sont au singulier)

Pour les routes : 
duplicates-document => document-duplicates

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +      })
Je ne comprends pas la justification. Oui il faut que le document existe pour créer un doublon. Mais ça ne conditionne en rien le droit de créer le doublon, c'est un droit différent non ? 

Auquel cas il faudrait l'ajouter dans la BD et utiliser : 
```js
      .with({
        groups: req.token.groups,
        rightEntity: RightService.RightEntities.DOCUMENT_DUPLICATE,
        rightAction: RightService.RightActions.CREATE,
      })
```

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    await Promise.all(createPromises);
Plutôt que d'utiliser `map` et `Promise.all`, c'est plus clair et plus performant d'utiliser `createEach()` [https://sailsjs.com/documentation/reference/waterline-orm/models/create-each](https://sailsjs.com/documentation/reference/waterline-orm/models/create-each)

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +      })
Même remarque sur le droit que plus haut.

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    const duplicate = await TDuplicateDocument.findOne(id);
Le helper checkIfExists fait exactement ça.

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +          'A server error occured when checking your right to delete an entrance duplicate.',
document duplicate (et non entrance)

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +        rightAction: RightService.RightActions.DELETE_ANY,
Même remarque que plus haut sur l'intitulé du droit.

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    return res.ok();
Il manque un try ... catch avec le ErrorService ici.

ok() renvoie un code 200, dans ce cas-là il vaut mieux renvoyer un 204 (no content).
Ou sinon réécrire la réponse ok() pour que quand on ne lui passe pas de paramètres, elle renvoie un 204.

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    return res.ok();
Même remarque que plus haut sur le try / catch et le ok().

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +        rightAction: RightService.RightActions.DELETE_ANY,
Même remarque sur le nom du droit (DOCUMENT => DOCUMENT_DUPLICATE)

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    }
Utiliser `ErrorService.getDefaultErrorHandler(res)(e);` plutôt (même si le message d'erreur ne sera pas aussi explicite, cela permet de gérer pleins d'autres types d'erreurs et de les logguer).

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    }
Utiliser le helper check-if-exists

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    duplicate.content = MappingV1Service.convertToDocumentModel(popDuplicate);
Pas de MappingService dans les Controllers ! 
Utilise le ControllerService avec le paramètre converter pour cela.

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    return res.ok(duplicates);
- try/catch avec le ErrorService
- utiliser le ControllerService avec un converter

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesEntranceController.js
> +        rightAction: RightService.RightActions.EDIT_ANY,
cf commentaire sur le nom du droit + c'est ENTRANCE ici

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesEntranceController.js
> +          'A server error occured when checking your right to create a document duplicate.',
entrance duplicate

2022-01-18 09:19 UTC, Clm-Roig commented on api/controllers/DuplicatesEntranceController.js
> +        'You are not authorized to create a document duplicate.',
entrance duplicate

2022-01-30 12:41 UTC, AxelCanton commented on api/controllers/DocumentController.js
> +};
Dans ma base de donnée dev (basé sur le mock) l'id est en iso3, c'est pour ça que mes tests ne fonctionnaient pas. C'est différent sur la bdd de prod ?

2022-01-30 12:46 UTC, AxelCanton commented on config/routes.js
> +  'GET /api/create-from-duplicates-document/:id':
Y'a pas de body, on se base sur ce qui a dans la table duplicate pour créer une ligne dans t_document ou t_entrance.

Pour la petite histoire, cette route est probablement inutile, ça devrait être possible à partir à partir de la route de création de le faire mais ça m'aurait demandé bcp plus de temps (et je commence à être limité en temps). De même pour la route updateWithNewEntities, il m'aurait fallut créer tous les actions/reducers (et routes si elles existent pas) pour créer les entités associées (descriptions, auteur, names..). Mais toujours dans un soucis de temps j'ai créer une nouvelle route.

2022-01-30 12:51 UTC, AxelCanton commented on api/services/DocumentService.js
> +  populateTable: async (document) => {
Oui je sais ! On en avait parlé pendant mon stage, ce qui est fait dans ce service est ce que je faisais dans l'import (j'ai refactor car je la réutilise du coup). Le problème est que je stocke dans json dans une colonne, et ces json ont le même schéma que la table, mais on peut pas populate sur le json d'un colonne (vu que c'est propre à postgres). J'avais 3 solutions : 
- créer une ligne temporaire, faire les populates, récupérer la donnée puis supprimer (mais pas possible car les données sont jamais supprimées dans la bdd, mais une colonne mise à true par un trigger)
- faire une requête sql (pas maintenable et honnêtement je sais pas si c'est faisable avec une colonne json)
- ou ce que j'ai fait

De souvenir tu avais validé cette solution (que j'avoue est très peu opti).

2022-01-30 12:55 UTC, AxelCanton commented on api/services/MappingV1Service.js
> +    result.intactDescriptions = source.descriptions;
Car j'ai des problèmes vis-à-vis de la séparation descriptions/titres (imho n'a pas trop de sens). Un titre est associé à une description mais ils sont clairement séparés, et dans le gestionnaire de doublon il n'y a pas de possibilité de choisir un titre sans choisir la description qui va avec.

2022-01-30 12:58 UTC, AxelCanton commented on api/services/DuplicateDocumentService.js
> +  create: async (authorId, content, documentId, date = null) => {
Je suis pas forcément d'accord avec toi ! Dans le cas des documents et entrances j'ai dû tout refactoriser pendant mon stage car je devais réutiliser la logique de création. Je vois pas en quoi le faire dès le début est un problème ? Ça évite de devoir repasser derrière mon code si un jour quelqu'un doit créer un duplicate sans réécrire le même code.

2022-01-30 13:10 UTC, AxelCanton commented on api/controllers/DocumentController.js
> +    }
Vu qu'on update l'entité avec cleanedData, si on ajoute pas les nouvelles donnée dans cleanedData, les relations seront supprimées.

2022-01-30 14:45 UTC, AxelCanton commented on api/controllers/DuplicatesDocumentController.js
> +    return res.ok();
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/204

Le nom porte à confusion mais de ce que je comprends ce n'est pas un body vide qui implique un status 204. Ça serait plutôt une modification qui devrait être invisible aux utilisateurs. Je pense que le 200 est correct dans ce cas. T'en penses quoi ?

2022-01-30 15:15 UTC, AxelCanton commented on api/controllers/DuplicatesDocumentController.js
> +    duplicate.content = MappingV1Service.convertToDocumentModel(popDuplicate);
ControllerService met fin à la requête et renvoie l'objet converti dans le body (ce que je veux pas). Je peux faire un converter qui applique le mapping sur les 2 attributs de mon objet, et renvoie l'object entier mais je vois pas la différence ?

2022-01-30 15:29 UTC, Clm-Roig commented on config/routes.js
> +  'GET /api/create-from-duplicates-document/:id':
> Y'a pas de body, on se base sur ce qui a dans la table duplicate pour créer une ligne dans t_document ou t_entrance.
> 
En RESTful API, la règle ce n'est pas "si body = POST (ou autre) sinon pas de body = GET." La règle c'est que s'il y a création de ressources ou lancement d'une action (exemple : POST /sendEmail), alors on utilise POST. 

> Pour la petite histoire, cette route est probablement inutile, ça devrait être possible à partir à partir de la route de création de le faire mais ça m'aurait demandé bcp plus de temps (et je commence à être limité en temps). 

D'accord, on la garde alors pour le moment. Je pense que ce serait bien que tu fasses des issues sur ce qu'il faut  améliorer à ce propos alors.

T'embête pas avec les modifs de code au pire, je m'en occuperai dans quelques semaines normalement.

2022-01-30 15:33 UTC, Clm-Roig commented on api/services/DocumentService.js
> +  populateTable: async (document) => {
Je m'en souviens vaguement, ça date je t'avoue ^^ 
La méthode doit s'appeler `populateJSON()` alors (avec un commentaire qui explique ce cas d'utilisation très particulier) , sinon on va croire que c'est la méthode "standard" de peuplement d'un document et on va l'utiliser partout (à tord).

2022-01-30 15:35 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    duplicate.content = MappingV1Service.convertToDocumentModel(popDuplicate);
> ControllerService met fin à la requête et renvoie l'objet converti dans le body (ce que je veux pas). 

Pourquoi tu ne veux pas mettre l'objet dans le body ?

> Je peux faire un converter qui applique le mapping sur les 2 attributs de mon objet, et renvoie l'object entier mais je vois pas la différence ?

Oui tu peux créer des nouveaux converters, c'est la bonne méthode. Ce serait un converter du genre `convertToDocumentDuplicateModel` par exemple.

2022-01-30 15:40 UTC, Clm-Roig commented on api/controllers/DocumentController.js
> +};
L'id de la table **t_language** n'est pas un country iso3. C'est un code à 3 lettres oui, mais pas le même que pour les pays. Tu utilises `getCountryISO3()` qui, par chance, fonctionne pour pas mal de pays (pays avec une seule langue, langue qui a le même code à 3 chiffres que le code du pays) mais qui ne fonctionnera pas pour tous. 

La preuve, tu as dû faire un cas particulier pour l'anglais car on n'a pas de pays "England" dans la BD mais seulement "United Kingdom".

2022-01-30 15:56 UTC, AxelCanton commented on api/controllers/DocumentController.js
> +};
Mais on envoie bien un code à 2 lettres par l'import, donc je devrais pas me baser sur l'id mais sur la colonne part1 de t_language ? Honnêtement j'ai dû mal à voir comment l'import marche à l'heure actuelle (si c'est le cas).

2022-01-30 16:05 UTC, Clm-Roig commented on api/controllers/DocumentController.js
> +};
L'import fonctionne très bien, Frédéric s'en est beaucoup servi ces deniers mois :) 

En tant qu'API, c'est à toi d'imposer à l'utilisateur de rentrer la bonne valeur. C'est ce que j'ai fait quand j'ai retiré cette fonction : j'ai dit à Frédéric d'utiliser désormais le code de langue au lieu du code pays et ça a marché.

2022-02-09 13:56 UTC, Clm-Roig commented
@AxelCanton est-ce que tu vas pousser du code qui corrige ce que j'ai mentionné ? Je veux bien m'en occuper mais vu que j'ai vu que tu avais marqué des conversations comme "résolues" sans pour autant qu'elles le soient sur la PR, je me dis que tu dois avoir des trucs en local.

2022-02-21 11:50 UTC, AxelCanton commented
J'ai en effet des modifications en local qui correspond à ce que j'ai mis en résolu. Je les push ce soir (désolé du temps de réponse).

2022-02-21 13:18 UTC, Clm-Roig commented
Ok ! Donc ça t'irait si à partir de demain je prends le relai sur cette PR ? (demain ou plus tard certainement)

2022-02-21 20:14 UTC, AxelCanton commented
Ca m'arrange beaucoup ! Vraiment désolé de te refiler le sale boulot comme ça. N'hésite pas à m'envoyer des messages sur Slack si t'as des questions, ou sur axelcanton01@gmail.com si je prends trop de temps à répondre.

2022-03-10 09:18 UTC, Clm-Roig commented on api/models/TDuplicateDocument.js
> +    date: {
`date_publication` plutôt que `date` pour rester cohérent avec ce qui existe déjà dans l'API.

2022-03-10 09:18 UTC, Clm-Roig commented on api/models/TDuplicateEntrance.js
> +    date: {
`date_publication` plutôt que `date` pour rester cohérent avec ce qui existe déjà dans l'API.

2022-03-10 09:31 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +        .populate('author');
Ajouter un paramètre facultatif `sortBy`

2022-03-12 08:53 UTC, Clm-Roig commented on api/controllers/DocumentController.js
> +          );
Après discussion avec Frédéric, ce code-là devrait être exécuté dans la fonction importRows plutôt.

2022-03-28 11:50 UTC, Clm-Roig commented on api/controllers/DuplicatesDocumentController.js
> +    return res.ok();
Hum, je reste sur ma position. L[a recommendation officielle (qui est bien au-dessus et plus précise que de la doc Mozilla) explique cela : ](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)
> A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity. 

On est bien dans le 2ème cas.

Une autre raison : [https://www.linkedin.com/pulse/delete-rest-200-204-response-code-abhijit-mazumder](https://www.linkedin.com/pulse/delete-rest-200-204-response-code-abhijit-mazumder)

Le passage qui nous intéresse : 
![image](https://user-images.githubusercontent.com/20704943/160391274-089d277a-e90b-47b7-81c2-8a441c507e2d.png)

En gros, le fait qu'on renvoie un 200 peut être le reflet du fait que la ressource n'est pas "vraiment" supprimée mais simplement marquée comme supprimée, ce qui implique de le signaler à l'utilisateur avec un content : d'où le 200.

Ici on supprime "vraiment" le doublon, donc le 204 a tout son sens : l'action DELETE a fonctionné, y a plus rien à voir.

2022-03-28 11:50 UTC, Clm-Roig commented on api/services/DuplicateDocumentService.js
> +  create: async (authorId, content, documentId, date = null) => {
ça se défend effectivement, je vais laisser ça comme ça

2022-03-28 19:50 UTC, Clm-Roig commented
Notes pour moi-même : 
- Traiter le retour **willBeCreatedAsDuplicates** de l'API quand on importe des données 
- Transposer tout ce qui a été fait dernièrement (non-commité) sur les entrances
- S'occuper du tableau de doublons

2022-03-29 10:34 UTC, Clm-Roig submitted a review, later dismissed

2022-03-30 07:59 UTC, merged