785 person edit
GrottoCenter/Grottocenter3 pull request #795
Opened 2022-04-13 15:09 UTC by lageta

fixes #785

2022-04-13 15:29 UTC, Clm-Roig commented on config/policies.js
>    'v1/convert/convert': true,
Attention ici, il y a une route "convert" à part, il faut laisser le commentaire et la séparer de caver.

2022-04-13 15:34 UTC, Clm-Roig commented on api/services/CaverService.js
> +      if (!(caver.mail.search(/@mail.no$/) === -1)) {
Tu peux n'en faire qu'un seul `if`.

```js
if (!(caver.mail.search(/@mail.no$/) === -1)) {
```
ça peut se simplifier en 
```js
if (caver.mail.endsWith('@mail.no')) {
```

C'est plus lisible et y a pas besoin de regexp.

2022-04-13 15:37 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +  // Check right (Admin can't edit mail and password, Caver can only edit itself)
`(Admin can't edit mail and password, Caver can only edit itself)` à retirer. 

Le principe d'utiliser les droits dans la BD c'est qu'à tout moment on peut en retirer et en enlever. Dans le code, on ne sait pas qui a droit ou pas. On sait juste si l'utilisateur peut ou pas, indépendamment de son rôle.

2022-04-13 15:39 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +      });
Est-ce qu'on ne pourrait tout simplement remplacer le `removeFromCollection` + `addToCollection` par `replaceCollection()` ? 

La doc est ici : https://sailsjs.com/documentation/reference/waterline-orm/models/replace-collection

2022-04-13 15:40 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +      delete req.organizations;
Inutile ça non ? On ne touche jamais aux données de la requête qui plus est.

2022-04-13 15:43 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +      updatedCaver.groups = updatedCaverOrg.groups;
Pas forcément nécessaire. Quand on update un caver, on n'a pas besoin de faire appel à `CaverService.getCaver()` qui est coûteuse en performance (peuplement de tous les champs, beaucoup de données à renvoyer). 

Renvoie directement `updatedCaver` avec juste les données de base. Le client fera une nouvelle requête s'il lui en faut plus.

2022-04-13 15:44 UTC, Clm-Roig requested changes
Cf mes autres commentaires.

2022-04-13 19:35 UTC, lageta commented on api/controllers/v1/caver/update.js
> +      updatedCaver.groups = updatedCaverOrg.groups;
Alors, ce que me renvoie update c'est une version de caver sans les organisations, documents etc... Je peux pas faire de populate dessus. Hors j'aimerai tester la bonne modification de mes organisations dans mon update.test.js  

Je peux juste renvoyer le callback de ma fonction update mais faire un getCaver dans mon test pour récupérer les organisations ? Le callback correspondra pas forcement au schéma d'un caver comme j'ai changé dans le swagger il manquera les documents et les groupes c'est pas gênant ?

2022-04-13 19:40 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +      updatedCaver.groups = updatedCaverOrg.groups;
C'est rigoureux tout ça, beau sens du détails ! 

Pour les tests, mon point de vue est le suivant. Sois tu considères que l'update doit retourner un objet complet. Et donc tu le testes.
(Comme je le disais dans mon précédent commentaire, je ne trouve pas ça utile et ça fait des donnés envoyées en plus. Peut-être que les bonnes pratiques REST disent l'inverse, il faut se renseigner et en tirer une conclusion pour notre cas).

Soit tu considères que l'update ne doit pas tout renvoyer. Dans ton test tu fais ton la vérification avec tous les moyens que tu as à ta disposition (CaverService ou même TCave si besoin), indépendamment de la route. Je crois qu'il y a un test qui fait appel à un modèle pour vérifier. Mais je ne sais plus lequel c'est. 

Pour Swagger, on n'a pas poussé le sens du détail jusqu'à différencier les types de retours. Toutes les collections (documents et groupes par exemple) peuvent être peuplées ou non, on ne garantit rien pour le moment.

2022-04-13 19:53 UTC, lageta commented on api/controllers/v1/caver/update.js
> +      updatedCaver.groups = updatedCaverOrg.groups;
Je pense que je vais simplement faire appel à CaverService dans mon test ça m'évitera de surcharger ma méthode et qu'au final elle soit moins lisible. En soi ma méthode ne sera utiliser qu'au moment de faire un submit dans un formulaire pour modifier des infos. Je pense qu'il y aura une redirection automatique vers une page de profil qui elle lancera un getCaver avec toute les infos.  Donc pas besoin que le update renvoi plein de données directement.

2022-04-13 21:14 UTC, Clm-Roig commented on api/controllers/v1/caver/update.js
> +      updatedCaver.groups = updatedCaverOrg.groups;
Voilà c'est typiquement le genre d'use case qu'on rencontre la plupart du temps, je suis d'accord 🙂

2022-04-14 09:14 UTC, Clm-Roig commented
Ton rebase ne s'est pas bien passé je crois : 
![image](https://user-images.githubusercontent.com/20704943/163353912-723f204e-60b6-4905-a085-847bd45912f2.png)

2022-04-14 09:25 UTC, lageta commented
> Ton rebase ne s'est pas bien passé je crois : ![image](https://user-images.githubusercontent.com/20704943/163353912-723f204e-60b6-4905-a085-847bd45912f2.png)

J'ai essayé de stash des commits inutiles et de rebase.

2022-04-14 09:50 UTC, Clm-Roig commented
On ne doit pas avoir un seul commit "Merge" de manière générale. Tes commits ont été dans une autre branche mais sont encore visibles je pense.

2022-04-14 09:50 UTC, Clm-Roig commented
Essaie l'interactive rebase de Git Kraken, c'est super intuitif et facile 🙂

2022-04-14 10:24 UTC, closed without merging

2022-04-15 23:29 UTC, bsoufflet commented
@lageta : Je pourrais vous faire une présentation rapide du git rebase interactif lors de notre prochaine visio. Fais y moi penser ;)