796 find name
GrottoCenter/Grottocenter3 pull request #828
Opened 2022-04-26 08:06 UTC by lageta

fix #796

2022-04-26 11:58 UTC, Clm-Roig requested changes

2022-04-26 11:58 UTC, Clm-Roig commented on api/services/CaverService.js
> +      await Promise.all(descriptionsArray).then((descritpionsCompleted) => {
Faute de frappe sur `descritpionsCompleted` => `descriptionsCompleted` (inversion t et p)
Mais de toute façon, à renommer `completedDescriptions` en anglais correct 😉

2022-04-26 11:58 UTC, Clm-Roig commented on api/services/CaverService.js
> +        }
Cette fonctionnalité est quasiment la même que `DescriptionService.setDocumentDescriptions` je pense. 

De manière générale, tu es dans le CaverService. Ici, tu ne dois rien faire de très "profond" en terme de peuplement autrement que ce qui est propre au Caver. Si tu te retrouves à faire ça, il faut le chercher ailleurs (ou le cas échéant, l'écrire ailleurs).

2022-04-29 15:30 UTC, Clm-Roig approved these changes

2022-04-29 16:27 UTC, merged

2022-04-29 20:58 UTC, bsoufflet commented
@Clm-Roig : Serait il possible de faire une release avec ces commits pour débloquer le dev front (afin qu'ils n'ai pas besoin de lancer le back en local) ?

2022-04-29 21:02 UTC, bsoufflet commented
@lageta : Une remarque pour tes prochaines PR : Il faut absolument réduire le nombre de commits avant de merge à un nombre de commit logique qui est en accord avec l'importance de la fonctionnalité...
Une mini fonctionnalité comme celle-ci mériterait plus 1 commit que 5 ;)
Pour faire cela il faut utiliser `git rebase -i develop` lorsque tu es sur ta branch. En mode interactif tu vas pouvoir utiliser les commandes suivantes sur tous les commits sauf le premier afin de réecrire l'historique de ta branche et n'avoir que 1 commit : 
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message

De manière général on devrait avoir 1 issue github  = 1 commit (sauf pour les très grosses fonctionnalités)

2022-04-29 21:03 UTC, Clm-Roig commented
> @Clm-Roig : Serait il possible de faire une release avec ces commits pour débloquer le dev front (afin qu'ils n'ai pas besoin de lancer le back en local) ?

Je fais ça dans l'heure !