844 organization tests populate
GrottoCenter/Grottocenter3 pull request #845
Opened 2022-05-08 15:48 UTC by lageta

fix #844

2022-05-08 18:45 UTC, Clm-Roig requested changes
Concernant le renommage "Organization" => "Grotto" des tests de routes, je pense qu'il est plus pertinent de garder "Organization".

On est encore sur "Grotto" pour le modèle mais partout ailleurs (action / controlleurs / routes), on a basculé sur "Organization" comme terme. Donc le test de la route concerne bien "Organization".

2022-05-08 18:45 UTC, Clm-Roig commented on api/services/GrottoService.js
> +      for (let i = 0; i < organization.documents.length; i += 1) {
```js
for (const document of organization.documents) { 
```
Plus concis et moderne :wink:

2022-05-08 18:45 UTC, Clm-Roig commented on test/integration/3_routes/Grottos/create.test.js
> +            should(organization.yearBirth).equal(2022);
Tu peux réutiliser ta variable `organizationToCreate` ici pour pas avoir à réécrire toutes ses valeurs.
Dans le test de l'upate de cave, j'avais écrit ce bout de code (ici adapté à ton cas) : 

```js
for (const key of Object.keys(organizationToCreate)) {
  should(cave[key]).equal(newValues[key]);
}
``

2022-05-08 18:45 UTC, Clm-Roig commented on test/integration/3_routes/Grottos/update.test.js
> +            );
Même chose que pour le test de create.

2022-05-11 18:44 UTC, Clm-Roig submitted a review, later dismissed

2022-05-11 22:09 UTC, lageta commented
J'ai cassé le déploiement parce que ai oublié un droit dans tgroup lors de la resolution de conflit 😅

2022-05-11 22:11 UTC, Clm-Roig approved these changes

2022-05-12 15:15 UTC, lageta commented
J'arrive pas à rebase et merge cette PR ... 😅 Cela ne me propose plus de résoudre les confits le bouton est disable.

2022-05-12 15:26 UTC, Clm-Roig commented
T'as fait un merge à minuit plutôt qu'un rebase :| ça complexifie un peu la tâche...

2022-05-13 08:32 UTC, Clm-Roig approved these changes

2022-05-13 15:03 UTC, merged